Add basic search and faceting functionality
ghga-de/metadata-search-service pull request #2
Opened 2021-12-03 07:49 UTC by deepakunni3

Title squash and merge:
```
Add basic search and faceting functionality
```

Description for squash and merge:
```
- Add implementation for enabling simple search for documents of a particular document type
- Add implementation for generating facets for a simple search query
```

**P.S:** The branch name was created before looking at the feedback from the other PR. Will be mindful of the branch name and format in the future.

2021-12-03 11:28 UTC, KerstenBreuer requested changes
Nice stuff 👍 

Just some comments to make it compliant with the API design we discussed.

2021-12-03 11:28 UTC, KerstenBreuer commented on metadata_search_service/api/main.py
> +async def search(query: str, document_type: DocumentType, facet: bool = False):
Here you are passing in all parameters via the URL ("query parameters"), however, we agreed on using the body for that. You have already created a model called `SearchQuery` in the `models.py`. You just have to use it here in the function header.

The additional `document_type` is also not compliant with the design we agreed on. The way to make it compliant is just reading it from the facet options.

2021-12-03 11:28 UTC, KerstenBreuer commented on metadata_search_service/api/main.py
> +async def search(query: str, document_type: DocumentType, facet: bool = False):
Please find more details in the comment on the `openapi.yaml`

2021-12-03 11:28 UTC, KerstenBreuer commented on metadata_search_service/dao/db.py
> +    config = get_config()
the function should get the config as argument

2021-12-03 11:28 UTC, KerstenBreuer commented on metadata_search_service/dao/document.py
> +            stats.update(nested_stats)
Very nice :)

2021-12-03 11:28 UTC, KerstenBreuer commented on openapi.yaml
> +          type: boolean
Please put this into the body as previously discussed here: https://github.com/ghga-de/milestones-docs/blob/main/epic_0_blob_fish/rest/metadata_search.yaml#L98-L104

The document type can be given as a facet, e.g. the request body might look like this:
```
{
    "q": "*",
    "facets": {
         "document_type": { 
               "option":  "Dataset"
          }
    }
}
```

Moreover, I noticed that you changed the "q" parameter to "query". Generally, I think that is not a bad idea but should we then also change that in our milestone-docs?

2021-12-03 11:28 UTC, KerstenBreuer commented on tests/integration/test_api.py
> +    assert response.text == '"Index for Metadata Search Service."'
Would be great to have a test for the actual `/rpc/search` endpoint.

2021-12-03 11:30 UTC, KerstenBreuer commented
Just one more general question, so in the current design there is no possibility to pass in any facet options (except of the document type) from the client?

(If so that is not a problem, we can add it later. Just wondering whether this was intended.)

2021-12-03 15:08 UTC, deepakunni3 commented on metadata_search_service/api/main.py
> +        raise HTTPException(status_code=400, detail="Unexpected search query pattern.")
👍

2021-12-03 15:09 UTC, deepakunni3 commented on metadata_search_service/config.py
> +    db_url: str = ""
👍

2021-12-03 15:09 UTC, deepakunni3 commented on metadata_search_service/dao/document.py
> +config = get_config()
Indeed, will follow the suggestions from the other PR 👍

2021-12-03 16:26 UTC, deepakunni3 commented on metadata_search_service/api/main.py
> +async def search(query: str, document_type: DocumentType, facet: bool = False):
Thanks for pointing that out. 

But I do want to make a case for having `document_type` and `facet` as part of the parameters. It becomes much easier to direct the search with `document_type`.

2021-12-03 16:27 UTC, deepakunni3 commented on metadata_search_service/dao/db.py
> +    config = get_config()
👍

2021-12-03 16:29 UTC, deepakunni3 commented on openapi.yaml
> +          type: boolean
Yes, thanks for pointing this out.

I made a PR (still WIP) on milestone-docs repo: https://github.com/ghga-de/epic-docs/pull/7 

I don't think it makes sense to overload facets with `document_type` unless `document_type` is a field on our metadata records (which is not the case). 
Instead, we need `document_type` as a parameter.

2021-12-03 16:29 UTC, deepakunni3 commented on tests/integration/test_api.py
> +    assert response.text == '"Index for Metadata Search Service."'
Yes, will add that as well.

2021-12-03 16:30 UTC, deepakunni3 commented
Not at the moment. I think the next pass will take care of /search endpoint supporting filters. One of such filters would be filtering via facets.

2021-12-03 20:04 UTC, KerstenBreuer commented on metadata_search_service/api/main.py
> +async def search(query: str, document_type: DocumentType, facet: bool = False):
OK, that makes a lot of sense. Thanks. I will add another PR to the epic_docs repo to include the document_type parametet

2021-12-03 20:05 UTC, KerstenBreuer commented on openapi.yaml
> +          type: boolean
Sounds good. I agree.

2021-12-06 06:03 UTC, deepakunni3 commented on metadata_search_service/api/main.py
> +async def search(query: str, document_type: DocumentType, facet: bool = False):
Thanks @KerstenBreuer 👍

2021-12-06 11:17 UTC, KerstenBreuer requested changes
Let's discuss the API changes. Otherwise all great.

2021-12-06 11:17 UTC, KerstenBreuer commented on metadata_search_service/api/main.py
> +    hits, facets = await get_documents(document_type, facet, skip, limit, config)
For such more complicated function calls (> 1 argument), could you please use kwargs? This makes it easier to read and safer to modify the function because we are not relying on the position but on the argument name.

2021-12-06 11:17 UTC, KerstenBreuer commented on metadata_search_service/api/main.py
> +    limit: int = 10,
Could we please discuss any changes to the API specs first. Either in person or at least via a PR to the epic-docs. Of course, you have a lot of freedom to choose the interface of pretty much any function but when it comes to a service API, I hope it's OK with you to always discuss possible changes before implementing them.

2021-12-06 11:17 UTC, KerstenBreuer commented on metadata_search_service/dao/db.py
> +    config = get_config()
I think this one you missed ;)

2021-12-06 11:17 UTC, KerstenBreuer commented on tests/integration/test_api.py
> +        assert len(data["facets"]) > 0
This is a very basic one but it will do for now 😆

2021-12-06 11:48 UTC, deepakunni3 commented on metadata_search_service/dao/db.py
> +    config = get_config()
D'oh!

2021-12-06 11:50 UTC, deepakunni3 commented on metadata_search_service/api/main.py
> +    hits, facets = await get_documents(document_type, facet, skip, limit, config)
👍

2021-12-06 12:11 UTC, KerstenBreuer approved these changes

2021-12-06 13:13 UTC, merged