Support filtering via keywords and facets (GDEV-391)
ghga-de/metadata-search-service pull request #8
Opened 2021-12-10 07:05 UTC by deepakunni3

Title for squash and merge:
```
Support filtering via keywords and facets
```

Description for squash and merge:
```
- Extend search functionality to support search by keywords
- Extend search functionality to support filters
- Extend search functionality to support facet filters
```

2021-12-15 14:31 UTC, KerstenBreuer requested changes
Thank you. Very nice.

Maybe we should consider moving code around a bit to:
- prevent circular imports
- achieve a clearer separation between the DAO and the business-logic

2021-12-15 14:31 UTC, KerstenBreuer commented on metadata_search_service/core/utils.py
> +    return pipelines
All of this is specific for MongoDB, right?

You might want to consider to move this code to the dao subpacke instead of the core as the core should not know about the underlying database technology. However, once we are going for elasticsearch, we might either way skip the DAO pattern entirely. So I think it is up to you where to put the code.

2021-12-15 14:31 UTC, KerstenBreuer commented on metadata_search_service/core/utils.py
> +        search_query: The search query string to use for text serach
```suggestion
        search_query: The search query string to use for text search
```

2021-12-15 14:31 UTC, KerstenBreuer commented on metadata_search_service/dao/document.py
> +)
To avoid circular dependencies, could you please follow this rule: core may import from dao but dao might not import from core.

2021-12-15 14:31 UTC, KerstenBreuer commented on metadata_search_service/dao/document.py
>  async def get_documents(
What are the different purposes of `get_documents` and `_get_documents`? Could we adapt the names and docstrings to reflect this difference?

2021-12-15 14:31 UTC, KerstenBreuer commented on metadata_search_service/dao/document.py
Could you specify what is in the Lists of the returned tuple? This applies to all the other similar functions, too.

2021-12-15 14:31 UTC, KerstenBreuer commented on tests/integration/test_api.py
>  )
Wow, this is a massive decorator 😄. Should I show you how we are doing tests in the other services? There is a way how to avoid this.

2021-12-15 14:31 UTC, KerstenBreuer commented on tests/test_data/data_access_committees.json
> +{
All could you mode all files from `tests/test_data` to either `tests/fixtures/data` or to `example_data/`?

2021-12-16 09:42 UTC, deepakunni3 commented on metadata_search_service/core/utils.py
> +        }:
Good point 👍

2021-12-16 09:43 UTC, deepakunni3 commented on metadata_search_service/core/utils.py
> +        }:
Went with the 2nd suggestion since the set is likely to have more than one field in the future.

2021-12-16 09:48 UTC, deepakunni3 commented on metadata_search_service/core/utils.py
> +    return pipelines
Excellent point. I think there will be some form of accessory code, be it ES or Mongo. I'll move it to a separate location in the `dao` module.

2021-12-16 09:49 UTC, deepakunni3 commented on tests/integration/test_api.py
>  )
Heh, yes. I would appreciate that :D

2021-12-16 09:49 UTC, deepakunni3 commented on tests/test_data/data_access_committees.json
> +{
Yes, will move to`tests/fixtures/data` 👍

2021-12-16 09:59 UTC, deepakunni3 commented on metadata_search_service/dao/document.py
> +)
Shouldn't it be the other way?

DAO can import from core since core is just service specific utilities?

2021-12-16 10:00 UTC, deepakunni3 commented on metadata_search_service/dao/document.py
>  async def get_documents(
Yes, I think most of this might go through a rewrite when we move to ES.

2021-12-16 10:04 UTC, deepakunni3 commented on metadata_search_service/dao/document.py
> +)
Hmmm, I think I must have misunderstood what core means here.
So the sequence of operations would be: api -> core -> dao

2021-12-16 10:06 UTC, KerstenBreuer commented on metadata_search_service/dao/document.py
> +)
Yes exactly. Core is using the database but shouldn't worry about it's underlying implementation.

And the API (RESTful as well as pub/sub) is using the core.

We should maybe document this in an SOP.

2021-12-16 10:08 UTC, KerstenBreuer commented on tests/integration/test_api.py
>  )
But for now it can actually stay this way. No need to delay this PR. I'll create a task for refactoring the test framework.

2021-12-16 10:08 UTC, KerstenBreuer commented on metadata_search_service/dao/document.py
>  async def get_documents(
OK, I see

2021-12-16 10:09 UTC, KerstenBreuer commented on metadata_search_service/core/utils.py
> +    return pipelines
Perfect, thanks

2021-12-16 10:42 UTC, deepakunni3 commented on metadata_search_service/dao/document.py
> +)
Got it. I refactored the code to better reflect this sequence

2021-12-16 10:44 UTC, deepakunni3 commented on metadata_search_service/dao/document.py
>  async def get_documents(
But I did change the names (and location) of the methods to better reflect the intent :)

2021-12-16 13:07 UTC, KerstenBreuer approved these changes
Looks good :)

2021-12-16 13:07 UTC, KerstenBreuer commented on metadata_search_service/dao/document.py
>  async def get_documents(
Great thanks

2021-12-16 13:08 UTC, merged